### ISSUE TITLE
Why it has to use function send() instead of sendline() in  CSAW 2016 hungman?

### ISSUE THREAD

**Issue by a7vinx** [ret2libc/ctfs#1]
I am confused with the use of function "send" in csaw2016 hungman, line 81, because if I use sendline() here instead of send(), the program will exit with code -11 before I can receive next "Continue? ".  In my view, the use of send() and sendline() should have the same result in the next code segment decompiled by IDA so I am very confused:

```
        namep = malloc(0xF8uLL);
        memset(namep, 0, 0xF8uLL);
        new_name_len = read(0, namep, 0xF8uLL);
        objp->name_len = new_name_len;
        v14 = strchr((const char *)namep, 10);
        if ( v14 )
          *v14 = 0;
        memcpy((void *)objp->namep, namep, new_name_len);// ---- overflow  
        free(namep);
```

Thanks for any help!

**Comment by a7vinx** [comment]
Oh...finally I find what's wrong with sendline()...The point is that strchr@got.plt is followed by printf@got.plt so that using sendline() will make new_name_len=9 and this will result in printf@got.plt being crashed. :)

**Comment by ret2libc** [comment]
Ops, sorry, I just saw your issue :( Glad you found the answer anyway!
